// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /tmp/doca-platform/config/provisioning/crd/bases/provisioning.dpu.nvidia.com_dpus.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "provisioning.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPU",
    plural = "dpus"
)]
#[kube(namespaced)]
#[kube(status = "DpuStatus")]
#[kube(schema = "disabled")]
pub struct DpuSpec {
    pub bfb: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "bmcIP")]
    pub bmc_ip: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cluster: Option<DpuCluster>,
    #[serde(rename = "dpuDeviceName")]
    pub dpu_device_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "dpuFlavor")]
    pub dpu_flavor: Option<String>,
    #[serde(rename = "dpuNodeName")]
    pub dpu_node_name: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeEffect"
    )]
    pub node_effect: Option<DpuNodeEffect>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "pciAddress"
    )]
    pub pci_address: Option<String>,
    #[serde(rename = "serialNumber")]
    pub serial_number: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuCluster {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeLabels"
    )]
    pub node_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeEffect {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "applyOnLabelChange"
    )]
    pub apply_on_label_change: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "customAction"
    )]
    pub custom_action: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "customLabel"
    )]
    pub custom_label: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub drain: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hold: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "noEffect")]
    pub no_effect: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeMaintenanceAdditionalRequestors"
    )]
    pub node_maintenance_additional_requestors: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub taint: Option<DpuNodeEffectTaint>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeEffectTaint {
    pub effect: String,
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "timeAdded")]
    pub time_added: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub addresses: Option<Vec<DpuStatusAddresses>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "bfCFGFile")]
    pub bf_cfg_file: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "bfbFile")]
    pub bfb_file: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "bfbVersion"
    )]
    pub bfb_version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpfVersion"
    )]
    pub dpf_version: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuInstallInterface"
    )]
    pub dpu_install_interface: Option<DpuStatusDpuInstallInterface>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "dpuMode")]
    pub dpu_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub firmware: Option<DpuStatusFirmware>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "pciDevice")]
    pub pci_device: Option<String>,
    pub phase: DpuStatusPhase,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "postProvisioningNodeEffect"
    )]
    pub post_provisioning_node_effect: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "requiredReset"
    )]
    pub required_reset: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuStatusAddresses {
    pub address: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuStatusDpuInstallInterface {
    #[serde(rename = "gNOI")]
    GNoi,
    #[serde(rename = "hostAgent")]
    HostAgent,
    #[serde(rename = "redfish")]
    Redfish,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuStatusFirmware {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bmc: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nic: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uefi: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuStatusPhase {
    Initializing,
    #[serde(rename = "Node Effect")]
    NodeEffect,
    Pending,
    #[serde(rename = "Config FW Parameters")]
    ConfigFwParameters,
    #[serde(rename = "Prepare BFB")]
    PrepareBfb,
    #[serde(rename = "OS Installing")]
    OsInstalling,
    #[serde(rename = "DPU Cluster Config")]
    DpuClusterConfig,
    #[serde(rename = "Host Network Configuration")]
    HostNetworkConfiguration,
    Ready,
    Error,
    Deleting,
    Rebooting,
    #[serde(rename = "Initialize Interface")]
    InitializeInterface,
    #[serde(rename = "Checking Host Reboot Required")]
    CheckingHostRebootRequired,
    #[serde(rename = "Node Effect Removal")]
    NodeEffectRemoval,
}
