// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /tmp/doca-platform/config/provisioning/crd/bases/provisioning.dpu.nvidia.com_dpunodemaintenances.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "provisioning.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUNodeMaintenance",
    plural = "dpunodemaintenances"
)]
#[kube(namespaced)]
#[kube(status = "DpuNodeMaintenanceStatus")]
#[kube(schema = "disabled")]
pub struct DpuNodeMaintenanceSpec {
    #[serde(rename = "dpuNodeName")]
    pub dpu_node_name: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeEffect"
    )]
    pub node_effect: Option<DpuNodeMaintenanceNodeEffect>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub requestor: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeMaintenanceNodeEffect {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "applyOnLabelChange"
    )]
    pub apply_on_label_change: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "customAction"
    )]
    pub custom_action: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "customLabel"
    )]
    pub custom_label: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub drain: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hold: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "noEffect")]
    pub no_effect: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeMaintenanceAdditionalRequestors"
    )]
    pub node_maintenance_additional_requestors: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub taint: Option<DpuNodeMaintenanceNodeEffectTaint>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeMaintenanceNodeEffectTaint {
    pub effect: String,
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "timeAdded")]
    pub time_added: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeMaintenanceStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "maxUnavailableDPUNodes"
    )]
    pub max_unavailable_dpu_nodes: Option<i32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "multiDPUOperationsSyncWaitTime"
    )]
    pub multi_dpu_operations_sync_wait_time: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeEffectSyncStartTime"
    )]
    pub node_effect_sync_start_time: Option<String>,
}
