// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /tmp/doca-platform/config/provisioning/crd/bases/provisioning.dpu.nvidia.com_dpuflavors.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "provisioning.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUFlavor",
    plural = "dpuflavors"
)]
#[kube(namespaced)]
#[kube(schema = "disabled")]
pub struct DpuFlavorSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "bfcfgParameters"
    )]
    pub bfcfg_parameters: Option<Vec<String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "configFiles"
    )]
    pub config_files: Option<Vec<DpuFlavorConfigFiles>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "containerdConfig"
    )]
    pub containerd_config: Option<DpuFlavorContainerdConfig>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "dpuMode")]
    pub dpu_mode: Option<DpuFlavorDpuMode>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuResources"
    )]
    pub dpu_resources: Option<BTreeMap<String, IntOrString>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub grub: Option<DpuFlavorGrub>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "hostNetworkInterfaceConfigs"
    )]
    pub host_network_interface_configs: Option<Vec<DpuFlavorHostNetworkInterfaceConfigs>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nvconfig: Option<Vec<DpuFlavorNvconfig>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ovs: Option<DpuFlavorOvs>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sysctl: Option<DpuFlavorSysctl>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "systemReservedResources"
    )]
    pub system_reserved_resources: Option<BTreeMap<String, IntOrString>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuFlavorConfigFiles {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operation: Option<DpuFlavorConfigFilesOperation>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permissions: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuFlavorConfigFilesOperation {
    #[serde(rename = "override")]
    Override,
    #[serde(rename = "append")]
    Append,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuFlavorContainerdConfig {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "registryEndpoint"
    )]
    pub registry_endpoint: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuFlavorDpuMode {
    #[serde(rename = "dpu")]
    Dpu,
    #[serde(rename = "zero-trust")]
    ZeroTrust,
    #[serde(rename = "nic")]
    Nic,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuFlavorGrub {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "kernelParameters"
    )]
    pub kernel_parameters: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuFlavorHostNetworkInterfaceConfigs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dhcp: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mtu: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub nvconfig: Option<DpuFlavorHostNetworkInterfaceConfigsNvconfig>,
    #[serde(rename = "portNumber")]
    pub port_number: i32,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuFlavorHostNetworkInterfaceConfigsNvconfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "hostPowerCycleRequired"
    )]
    pub host_power_cycle_required: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuFlavorNvconfig {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "hostPowerCycleRequired"
    )]
    pub host_power_cycle_required: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuFlavorOvs {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "rawConfigScript"
    )]
    pub raw_config_script: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuFlavorSysctl {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<String>>,
}
