// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /tmp/doca-platform/config/provisioning/crd/bases/provisioning.dpu.nvidia.com_dpusets.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use std::collections::BTreeMap;

    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "provisioning.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUSet",
    plural = "dpusets"
)]
#[kube(namespaced)]
#[kube(status = "DpuSetStatus")]
#[kube(schema = "disabled")]
pub struct DpuSetSpec {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuNodeSelector"
    )]
    pub dpu_node_selector: Option<DpuSetDpuNodeSelector>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuSelector"
    )]
    pub dpu_selector: Option<BTreeMap<String, String>>,
    #[serde(rename = "dpuTemplate")]
    pub dpu_template: DpuSetDpuTemplate,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub strategy: Option<DpuSetStrategy>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetDpuNodeSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<DpuSetDpuNodeSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetDpuNodeSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetDpuTemplate {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub spec: Option<DpuSetDpuTemplateSpec>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetDpuTemplateSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bfb: Option<DpuSetDpuTemplateSpecBfb>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cluster: Option<DpuSetDpuTemplateSpecCluster>,
    #[serde(rename = "dpuFlavor")]
    pub dpu_flavor: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeEffect"
    )]
    pub node_effect: Option<DpuSetDpuTemplateSpecNodeEffect>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetDpuTemplateSpecBfb {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetDpuTemplateSpecCluster {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeLabels"
    )]
    pub node_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetDpuTemplateSpecNodeEffect {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "applyOnLabelChange"
    )]
    pub apply_on_label_change: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "customAction"
    )]
    pub custom_action: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "customLabel"
    )]
    pub custom_label: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub drain: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hold: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "noEffect")]
    pub no_effect: Option<bool>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeMaintenanceAdditionalRequestors"
    )]
    pub node_maintenance_additional_requestors: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub taint: Option<DpuSetDpuTemplateSpecNodeEffectTaint>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetDpuTemplateSpecNodeEffectTaint {
    pub effect: String,
    pub key: String,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "timeAdded")]
    pub time_added: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetStrategy {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "rollingUpdate"
    )]
    pub rolling_update: Option<DpuSetStrategyRollingUpdate>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub r#type: Option<DpuSetStrategyType>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetStrategyRollingUpdate {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "maxUnavailable"
    )]
    pub max_unavailable: Option<IntOrString>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuSetStrategyType {
    OnDelete,
    RollingUpdate,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuSetStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuStatistics"
    )]
    pub dpu_statistics: Option<BTreeMap<String, i64>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "observedGeneration"
    )]
    pub observed_generation: Option<i64>,
}
