// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /tmp/doca-platform/config/provisioning/crd/bases/provisioning.dpu.nvidia.com_dpunodes.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "provisioning.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUNode",
    plural = "dpunodes"
)]
#[kube(namespaced)]
#[kube(status = "DpuNodeStatus")]
#[kube(schema = "disabled")]
pub struct DpuNodeSpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dpus: Option<Vec<DpuNodeDpus>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeDMSAddress"
    )]
    pub node_dms_address: Option<DpuNodeNodeDmsAddress>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "nodeRebootMethod"
    )]
    pub node_reboot_method: Option<DpuNodeNodeRebootMethod>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeDpus {
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeNodeDmsAddress {
    pub ip: String,
    pub port: i64,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeNodeRebootMethod {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub external: Option<DpuNodeNodeRebootMethodExternal>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "gNOI")]
    pub g_noi: Option<DpuNodeNodeRebootMethodGNoi>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "hostAgent")]
    pub host_agent: Option<DpuNodeNodeRebootMethodHostAgent>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub script: Option<DpuNodeNodeRebootMethodScript>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeNodeRebootMethodExternal {}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeNodeRebootMethodGNoi {}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeNodeRebootMethodHostAgent {}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeNodeRebootMethodScript {
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuNodeStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "dpuInstallInterface"
    )]
    pub dpu_install_interface: Option<DpuNodeStatusDpuInstallInterface>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "kubeNodeRef"
    )]
    pub kube_node_ref: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "rebootInProgress"
    )]
    pub reboot_in_progress: Option<bool>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum DpuNodeStatusDpuInstallInterface {
    #[serde(rename = "gNOI")]
    GNoi,
    #[serde(rename = "hostAgent")]
    HostAgent,
    #[serde(rename = "redfish")]
    Redfish,
}
