// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /tmp/doca-platform/config/provisioning/crd/bases/provisioning.dpu.nvidia.com_dpudevices.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "provisioning.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "DPUDevice",
    plural = "dpudevices"
)]
#[kube(namespaced)]
#[kube(status = "DpuDeviceStatus")]
#[kube(schema = "disabled")]
pub struct DpuDeviceSpec {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "bmcIp")]
    pub bmc_ip: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "bmcPort")]
    pub bmc_port: Option<i32>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "numberOfPFs"
    )]
    pub number_of_p_fs: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opn: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "pf0Name")]
    pub pf0_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub psid: Option<String>,
    #[serde(rename = "serialNumber")]
    pub serial_number: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DpuDeviceStatus {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "bmcIp")]
    pub bmc_ip: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "bmcPort")]
    pub bmc_port: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "dpuMode")]
    pub dpu_mode: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub opn: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "pciAddress"
    )]
    pub pci_address: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "pf0Mac")]
    pub pf0_mac: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "pf0Name")]
    pub pf0_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub psid: Option<String>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "serialNumber"
    )]
    pub serial_number: Option<String>,
}
