---
lint:
  rules:
    no_default: true

    add:
      - ENUM_NAMES_UPPER_CAMEL_CASE  # Verifies that all enum names are CamelCase (with an initial capital).
      - FILE_NAMES_LOWER_SNAKE_CASE  # Verifies that all file names are lower_snake_case.proto. 
      - FIELD_NAMES_LOWER_SNAKE_CASE  # Verifies that all field names are underscore_separated_names.
      - IMPORTS_SORTED  # Verifies that all imports are sorted. 
      - MESSAGE_NAMES_UPPER_CAMEL_CASE  # Verifies that all message names are CamelCase (with an initial capital).
      - ORDER  # Verifies that all files should be ordered in the specific manner.
      - PACKAGE_NAME_LOWER_CASE  # Verifies that the package name should not contain any lowercase letters.
      - RPC_NAMES_UPPER_CAMEL_CASE  # Verifies that all rpc names are CamelCase (with an initial capital).
      - SERVICE_NAMES_UPPER_CAMEL_CASE  # Verifies that all service names are CamelCase (with an initial capital).
      - INDENT  # Enforces a consistent indentation style. ( 2 spaces )
      - PROTO3_FIELDS_AVOID_REQUIRED  # Verifies that all fields should avoid required for proto3.
      - PROTO3_GROUPS_AVOID  # Verifies that all groups should be avoided for proto3.

    remove:
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE  # Verifies that all enum field names are CAPITALS_WITH_UNDERSCORES.
      - ENUM_FIELD_NAMES_PREFIX  # Verifies that enum field names are prefixed with its ENUM_NAME_UPPER_SNAKE_CASE.
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH  # Verifies that the zero value enum should have the suffix "UNSPECIFIED". 
      - MAX_LINE_LENGTH  # Enforces a maximum line length. 
      - REPEATED_FIELD_NAMES_PLURALIZED  # Repeated field names should be pluralized.