apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: carbide
build:
  tagPolicy:
    sha256: {}
  local:
    push: false
    useBuildkit: true
    useDockerCLI: true
  artifacts:
    - image: carbide-dns
      sync:
        infer:
          - "carbide-dns"
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.dns.localdev
    - image: carbide-pxe
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.pxe.localdev
      sync:
        infer:
          - "carbide"
          - pxe/templates/*
          - pxe/static/*
    - image: nginx
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.nginx.localdev
      sync:
        infer:
          - "carbide"
          - pxe/static/*
    - image: carbide-api
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.api.localdev
      sync:
        infer:
          - "carbide-api"
          - api/casbin-policy.csv
          - pxe/static/*
    - image: forge-admin-cli
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.forge-admin-cli.localdev
      sync:
        infer:
          - "forge-admin-cli"
    - image: carbide-dhcp-server
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.dhcpserver.localdev
      sync:
        infer:
          - "forge-dhcp-server"
    - image: carbide-dhcp
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.dhcp.localdev
      sync:
        infer:
          - "libdhcp.so"
    - image: bmc-mock
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.bmc-mock.localdev
      sync:
        infer:
          - "bmc-mock"
    - image: machine-a-tron
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.machine-a-tron.localdev
      sync:
        infer:
          - "machine-a-tron"
    - image: nvmetal-scout-burn-in
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.machine-validation-config.localdev
      sync:
        infer:
          - "nvmetal-scout-burn-in"
    - image: carbide-hardware-health
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.health.localdev
      sync:
        infer:
          - "hw-health"
    - image: ssh-console-rs
      docker:
        dockerfile: dev/deployment/localdev/Dockerfile.ssh-console.localdev
      sync:
        infer:
          - "ssh-console"
manifests:
  kustomize:
    paths:
      - forged/envs/local-dev/site/site-controller
    buildArgs: ["--enable-alpha-plugins", "--enable-exec"]

deploy:
  kubeContext: k3s-dev
  kubectl:
    defaultNamespace: forge-system
  statusCheckDeadlineSeconds: 60
  tolerateFailuresUntilDeadline: true

