#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
    # TODO:  is this needed for scout?
	# Ensure the core file directory exists
	# Must match /proc/sys/kernel/core_pattern
	# mkdir -p /var/support/core

	systemctl daemon-reload
	systemctl enable forge-scout.service

	# Do not depend on starting services now, as this package is installed early in setup
	# and should not hang or cause out of order steps in discovery workflows. The discovery
	# workflow will reboot shortly after this package is installed, so it is best to rely
	# on the reboot process to start the services enabled above.

	#if [ -n "$2" ]; then
 		# The package is being upgraded and not installed for the first time...
	#fi
fi
