FROM urm.nvidia.com/swngc-ngcc-docker-local/forge/carbide/x86-64/build-container:latest

RUN mkdir /target
RUN mkdir -p /cache/cargo
ENV SCCACHE_CACHE_SIZE 10g
ENV SCCACHE_DIR /cache/sccache
ENV CARGO_HOME /cache/cargo
ENV CARGO_TARGET_HOME /target
ENV RUSTC_WRAPPER /usr/local/cargo/bin/sccache
WORKDIR ./carbide
ENTRYPOINT ["cargo", "build", "-p"]
