# syntax=docker/dockerfile:1.4

# SPDX-FileCopyrightText: Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
FROM runtime-container-localdev:latest as carbide
WORKDIR ./carbide

COPY ".skaffold/target/carbide-dhcp/debug/libdhcp.so" "/usr/lib/x86_64-linux-gnu/kea/hooks"
