# SPDX-FileCopyrightText: Copyright (c) 2021-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
FROM debian:12-slim

# Set in gitlab-templates/scripts/build-push-container-image.sh
ARG CI_COMMIT_SHORT_SHA
ENV CI_COMMIT_SHORT_SHA $CI_COMMIT_SHORT_SHA

# Change CACHEKEY to whatever so docker doesn't re-use the cache from before if you want apt to actually run.
#
# https://github.com/moby/moby/issues/1996
# https://github.com/moby/buildkit/issues/4294
#
# Install CA certificates first so fluentbit works.  This is why there's two
# separate apt install lines, and we don't delete the /var/lib/apt/lists here
#
RUN CACHEKEY=${CI_COMMIT_SHORT_SHA} apt-get update && \
	DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt upgrade -y && \
	DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y --no-install-recommends ca-certificates

# Use fluentbit for logging (used by ssh-console)
COPY dev/docker/fluentbit.key /usr/share/keyrings/fluentbit-keyring.gpg
COPY dev/docker/fluentbit.list /etc/apt/sources.list.d/fluentbit.list

# This is required for kea pid file
RUN mkdir -p /var/run/kea

# Change CACHEKEY to whatever so docker doesn't re-use the cache from before if you want apt to actually run.
#
# https://github.com/moby/moby/issues/1996
# https://github.com/moby/buildkit/issues/4294
#
RUN CACHEKEY=${CI_COMMIT_SHORT_SHA} apt-get update && \
	DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y --no-install-recommends \
		curl \
		fluent-bit \
		ipmitool \
		iproute2 \
		iputils-ping \
		kea-dhcp4-server \
    kea-ctrl-agent \
		libaio1 \
		libc-ares2 \
		libgrpc++1.51 \
		libkrb5-3 \
		libprotoc32 \
		libssh-4 \
		libudev1 \
		nginx \
		openipmi \
		openssh-client \
		openssh-server \
		postgresql-client-15 \
		tpm2-tools \
		zlib1g && \
	rm -rf /var/lib/apt/lists/*
